### ISSUE TITLE
Pipe CSV data into Snowflake

### ISSUE THREAD

**Issue by ThomasLaPiana** [ethyca/fides-stats#1]
Need to set up a simple script to pipe the data into our Snowflake instance after the job runs

**Comment by iamkelllly** [comment]
Because Github repository stats are only kept for 2 weeks on a rolling basis, we need to find a more permanent home for this information. Using this information, we can gather analytics and infer insights about engagement and adoption of our projects. 

The requirement here is to:
* capture the following data from each of our github repos (`fides`, `fideslang`, `fidesops`) to a place where it can persist permanently:
  * stargazers
  * forks
  * views (total and unique) 
  * clones (total and unique)
  * top referrers
  * top paths
* allow a product manager or other data analyst to aggregate, and perform BI/reporting functions on the data; querying, sorting/filtering, and dashboard metric tracking

**Comment by ThomasLaPiana** [comment]
sounds good, I'll write a script that just pushes data continually to snowflake from here
